version: "3"
services:
  react-app:
    build: frontend/ml-capstone/.
    ports:
      - "3000:80"
    volumes:
      - ./frontend/ml-capstone/src:/app/src
  capstone-api:
    build: api/.
    ports:
      - "80:80"
    volumes:
      - ./api/app:/code/app
